src/index.html
src/index1.html

Se crearon los botones de conocer más, filtrar, ordenar y volver. Se agregó el párrafo de la pagina principal

Botones y pagina principal

---

src/dataFunctions.js
src/index.html
src/main.js
src/view.js

Se crearon variables y cajas para empezar a mostrar las tarjetas, falta escapar el codigo y seguir revisando el material sobre la iteración y renderizar

se crea caja de variables para mostrar tarjetas

---

src/view.js

Se muestran las tarjetas con descripción e imagen

Se muestran tarjetas una a una con la data

---

src/data/dataset.js
src/index.html
src/main.js

se modifica main y evento de ordenar

---

src/data/dataset.js
src/dataFunctions.js
src/index.html
src/main.js

Update en data function, dataset y mainjs

---

src/data/dataset.js
src/main.js
src/style.css
src/view.js

Se ajusta error en data set y se especifica dirección en view de estilos css

se modifica dataset, css y view

---

src/dataFunctions.js
src/index.html
src/main.js

Cambios Emma

---

src/index.html
src/view.js

Se modifica index para llamar al evento y los div en view

se modifica index y view

---

src/main.js
src/style.css
src/view.js

Se actualiza view js quitando los div y dejndo li con su respectiva clase, se modifican estilos en css

Feature rosa 1

---

src/index.html
src/style.css

Se borraron dos contenedores en index html que generaban conflictos en main

se corrigieron conflictos en main en el index.html

---

src/data/dataset.js
src/dataFunctions.js
src/index.html
src/main.js
src/style.css

Se realiza revert de la rama main y e deja versión del 201023 ajustando los conflictos

Se realiza revert versión 20-10-23

---

src/dataFunctions.js
src/index.html
src/main.js
src/view.js

Cambios en dataset, datafuntion,index,main y view.

Cambios en dataset, datafuntion,index,main y view

---

src/index.html

Se modifica select dejando el ordenado por modelo

se modifica select de ordenado

---

src/style.css

Se comentan estilos para avanzar en diseño

se modifica css

---

src/data/dataset.js
src/dataFunctions.js
src/index.html
src/main.js
src/style.css
src/view.js

Modificaciones en :       
modified:   src/data/dataset.js
modified:   src/dataFunctions.js
modified:   src/index.html
modified:   src/main.js
modified:   src/style.css
modified:   src/view.js

modificaciones en todas las ramas

---

src/index.html
src/main.js
src/view.js

Modificaciones en OH

---

src/style.css

Modificaciones para que se vea en columnas!

Modificaciones en css

---

src/index.html

Cambio por equivocación en index

Cambio por equivocación en index

---

src/dataFunctions.js
src/index.html
src/main.js
src/style.css

Se actualiza main y funtion para mostrar estadísticas de cada año, se modifican el filtro por años y se pone estilos al botón

se modifica estadistica y filtro por año, se crea animación en css

---

src/dataFunctions.js
src/index.html
src/main.js
src/style.css

Modifique cambios duplicados, por eso no se veian los cambios que realizaste.

Ya se ven los cambios

---

test/data.js
test/dataFunctions.spec.js

Modificaciones en Pruebas unitarias y data para realizarlas

Modificaciones en Pruebas unitarias y data para realizarlas

---

src/index.html
src/main.js
src/style.css
src/view.js
test/dataFunctions.spec.js

1. Modificaciones en css - media query - responsive mobile only.
2. Modificación en HTML (por actualización de css)

Modificaciones en css - media query - responsive mobile only

---

src/main.js
src/view.js
test/dataFunctions.spec.js

Se modificón el llamado de funciones desde el import de test unitarios y se modificó el responsive en ccs!

Modificaciones en test unitarios y ccs

---

src/dataFunctions.js
src/index.html
src/main.js
test/dataFunctions.spec.js

Se corrigen los filtros y el ordenamiento para mejorar la experiencia, se modifica la estadistica y se corrigen los test

se corrigen filtros y test

---

src/index.html
test/dataFunctions.spec.js

Se modifica Index.HTMl por error en semántica, para aprobar test html.

Modificaciones por falla en test

---

package.json
src/Readme.md
src/dataFunctions.js
src/index.html
src/main.js
src/style.css

Se deja el año que más modelos generó y se corrigen errores en pruebas oas

se corrigen errores de test y se incluye estadistica

---

src/dataFunctions.js
test/dataFunctions.spec.js

Se crea test para la función create element

se crea test de crear elementos en pantalla

---

test/dataFunctions.spec.js

Se modifica el test, sigue sin funcionar

Modificación del test de crear elementos
